#ifndef CONSTANTS_H_
	#define CONSTANTS_H_

	// ROBOT MOTOR GPIOS
	#define GPIO_M1_IN 21
	#define GPIO_M2_IN 22
	#define GPIO_M1_PWM 23
	#define GPIO_M2_PWM 26

	// ROBOT CONSTANTS
	#define PWM_MIN_VALUE 0
	#define PWM_MAX_VALUE 100
	#define FORWARD 1
	#define BACKWARD 0
	#define ROBOT_BASE_SPEED 50

	// SPI CHANNEL
	#define DISTANCE_CHANNEL 0
	#define BATTERY_CHANNEL 1

	// DISTANCE CONSTANTS
	#define SECURITY_DISTANCE 50

	// QTR8-RC SENSOR GPIOS
	#define GPIO_QTR_SENSOR_0 0
	#define GPIO_QTR_SENSOR_1 2
	#define GPIO_QTR_SENSOR_2 3
	#define GPIO_QTR_SENSOR_3 25
	#define GPIO_QTR_SENSOR_4 1
	#define GPIO_QTR_SENSOR_5 4
	#define GPIO_QTR_SENSOR_6 5
	#define GPIO_QTR_SENSOR_7 6

	// VARIABLES FOR PD CONTROL
	#define PROPORTIONAL_CONSTANT 6.5
	#define DERIVATIVE_CONSTANT 5.05


#endif // CONSTANTS_H_